cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  image: ${docker_registry}redhawk/maven:3-jdk-8
  stage: build
  tags:
    - ide
  script:
    - mvn install sonar:sonar -P sign -P develop-2.3 -P with-metadata -D maven.test.failure.ignore=true
  artifacts:
    paths:
      - tests/*/target/surefire-reports/*.xml
    expire_in: 1 day
  except:
    - master
    - /^(\d+\.)?(\d+)?(\.\d+)$/
    - /.*-external$/

