cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - cache/maven.repository
variables:
  DOCKER_REGISTRY_URL: ''
  P2_PATH: $CI_PROJECT_NAME/updates
mvn:
  image: ${DOCKER_REGISTRY_URL}redhawk/maven:3-jdk-8
  stage: build
  script:
    - mvn install sonar:sonar -P sign -P develop-2.1 -P with-metadata -Dmaven.repo.local=`pwd`/cache/maven.repository
  artifacts:
    paths:
      - releng/p2/target/*.zip
      - releng/p2/target/repository/**/*
      - releng/p2/target/repository/*.jar
    expire_in: 3 days
deploy:
  image: ${DOCKER_REGISTRY_URL}redhawk/deploy
  stage: deploy
  tags:
    - deployment
  dependencies:
    - mvn
  script:
    - eval "$(ssh-agent -s)"
    - ssh-add
    - rsync -avz --delete releng/p2/target/repository/* $PUBLISH_URL:$PUBLISH_PATH/$P2_PATH/$CI_BUILD_REF_NAME/
